from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Account',
    'Session',
    'Board',
    'Pin',
    'Comment',
    'Like',
    'Save',
    'Follow',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'accounts': 'Account',
        'sessions': 'Session',
        'boards': 'Board',
        'pins': 'Pin',
        'comments': 'Comment',
        'likes': 'Like',
        'saves': 'Save',
        'followers': 'Follow',
        'following': 'Follow',
    },
    'Account': {
        'user': 'User',
    },
    'Session': {
        'user': 'User',
    },
    'Board': {
        'user': 'User',
        'pins': 'Pin',
    },
    'Pin': {
        'user': 'User',
        'board': 'Board',
        'comments': 'Comment',
        'likes': 'Like',
        'saves': 'Save',
    },
    'Comment': {
        'pin': 'Pin',
        'user': 'User',
    },
    'Like': {
        'user': 'User',
        'pin': 'Pin',
    },
    'Save': {
        'user': 'User',
        'pin': 'Pin',
    },
    'Follow': {
        'follower': 'User',
        'following': 'User',
    },
}

# fmt: on